### ISSUE TITLE
Toolchain to build WindFlow 2.2.0 examples on MacOS

### ISSUE THREAD

**Issue by ricardopieper** [ParaGroup/WindFlow#1]
Hi @mencagli,

I'm having some trouble running make on the most recent version of WindFlow. I use MacOS mojave. `g++ --version` returns  `Apple LLVM version 10.0.1 (clang-1001.0.46.4)`. G++ is mapped to clang somehow.

In our classes I saw that you use a Mac as well, so I suppose you successfully builds WindFlow examples. However, when I try it, the following compilation error happens on a file inside the `includes` folder:

```
In file included from test_mp_kf+pf_cb.cpp:42:
In file included from ../../includes/windflow.hpp:34:
../../includes/builders.hpp:1586:43: error: no matching function for call to 'get_tuple_t'
    using panefarm_t = Pane_Farm<decltype(get_tuple_t(func_F)),
```

Since the error comes from the template library, I think it would prevent me from using it

I'll try using older versions just to check if they build successfully. I'll also try to change the toolchain to the real GCC one, or update to Catalina in the hopes it upgrades clang as well. So my question also is: which toolchain you currently use run Windflow?

**Comment by ricardopieper** [comment]
Perhaps it's just that file causing the compilation error on templates. merge_test works normally.

**Comment by mencagli** [comment]
I never compiled WindFlow on clang. Please use gnu compiler (gcc) at least version >=7. I always used WindFlow on Unix/Linux servers.   I will have a look at clang in the future. Full support is for gnu compiler.

**Comment by ricardopieper** [comment]
I have good news. Although support is only for GNU, Clang seems to be working as well. I'll attempt to run it on Ubuntu later to check if `test_mp_kf+pf_cb.cpp` compiles. All other files are compiling, and merge_test shows success:

```
$ ./test_merge_1 -r 1 -l 1000 -k 3
Run 0
+---------------------+
|  +-----+   +-----+  |
|  |  S  |   |  M  |  |
|  | (2) +-->+ (5) |  +------------+    +---------------------+
|  +-----+   +-----+  |            |    |  +-----+   +-----+  |
+---------------------+            |    |  |  M  |   |  S  |  |
                                   +--->+  | (5) +-->+ (1) |  |
+-------------------------------+  |    |  +-----+   +-----+  |
|  +-----+   +-----+   +-----+  |  |    +---------------------+
|  |  S  |   |  F  |   |  M  |  |  |
|  | (7) +-->+ (8) +-->+ (3) |  +--+
|  +-----+   +-----+   +-----+  |
+-------------------------------+
WindFlow Status Message: PipeGraph [test_merge_1] is running with 31 threads
Received 27000 results, total sum -149976000
WindFlow Status Message: PipeGraph [test_merge_1] executed successfully
Result is --> OK!!!
```

Closing this issue since it seems to work.
