### ISSUE TITLE
Send EventId along the Pipeline

### ISSUE THREAD

**Issue by raytangRT** [ParaGroup/WindFlow#5]
Hi, 

I am using this library to build a calculation pipeline (An Event-Driven pipeline source from Kafka). 
And I am trying to use `RuntimeContext` to share the eventId in downstream operators (so that I can have better visibility on how the calculation steps are).

But I see that  `RuntimeContext` is not shared between operators, and I don't want to include this `EventId` in my pipeline's messages. so any idea? 

Thanks

**Comment by mencagli** [comment]
Hi,

first of all apologize me for the delay of my answer. To have faster responses from my side, please send me an email.

About your message, I did not understand your issue. What is and event id? Is it an unique identifier?

In general, you can share any object by all operators of the DAG. To do that, you can simply provide the pointer/reference to that object to the constructors of the functor objects used to instantiate your operators through the corresponding builders. So doing, all operators (and all their replicas) will share the same pointer and can access the same data structure in memory. Of course, any problem related to race conditions (if you read/write shared data) is your responsibility (you have to add synchronizations in the operator code to manipulate shared data structures as usual in concurrent/parallel programming).

I hope this may help.

Best,

Gabriele

**Comment by raytangRT** [comment]
Thanks, I will try to use pointers for this
