### ISSUE TITLE
Disabling CPU affinity of auxiliary nodes to separate cores

### ISSUE THREAD

**Issue by vss888** [ParaGroup/WindFlow#6]
First, you have created an awesome product! Thank you! We use it and we love it - very fast, reliable, and convenient.

I do have one issue (related to optimization of how CPU cores are used) that I am trying to resolve. In my test, I have created a very simple graph consisting of one source and one sink (both with parallelism=1). And then I checked the number of nodes in the graph `graph.getNumThreads()` which is equal to 2 as expected. When I run the code and look at the threads in Linux _top_, I can see that indeed only 2 threads are run. However, in the destructor of (_fastflow_) `~ff_node`, I have added printing of what CPU core a given node was set affinity to, and I can see that actually 3 nodes are destroyed and each of them is pinned to a different CPU core (0,1,2) but the `myid` of the nodes are 0,1,0, so it seems that 2 nodes are actually copies of each other but they are still pinned to different CPU cores and only one of them is actually run in the code (the nodes pinned to cores 0 and 1 are run, and the node pinned to core 2 does nothing according to _top_):

``` none
// printouts by ff_node::~ff_node
CPUId: 0 myid:0
CPUId: 1 myid:1
CPUId: 2 myid:0
```

So, to improve the number of CPU cores which are available for nodes doing actual computing, how can I disable setting CPU affinity for the node, which ends up not being used in the graph?

Thank you very much for your help!

**Comment by mencagli** [comment]
Dear vss888,

WindFlow, for several internal implementation reasons, spawns an additional FastFlow node (run by a dedicated thread) in addition to the ones of your PipeGraph. This node, and so its underlying thread, terminates immediately after the application has been launched by the user with graph.run(). In your case this is the third node that is pinned on CPU2. It is not a copy of the node running on CPU0, it is a special self-killer node (see selfkiller_node struct in multipipe.hpp). It is strange that it has the same myid of the first node on CPU0. How do you get this myid? If you send me the source code of your example I can check tomorrow.

However, in your example the Source will run on CPU0, the Sink on CPU1 e no other threads are running (the self-killer node on CPU2 terminates immediately). This is perfectly fine.

In general, if you have for example only four CPUs in your machine, CPU0, CPU1, CPU2, CPU3 and you run a MultiPipe of four operators (each with parallelism 1 and not chained with the previous operator), you have four threads running on CPU0, CPU1, CPU2 and CPU3 respectively if you enable pinning. The hidden self-killer node/thread will be spawn and run on CPU0 in that case (circular assignment), but it terminates immediately and so it does not bother the processing of the first operator running on the same core CPU0.

If you answer this issue on GitHub, please send me an email to inform me, I seldomly access GitHub and I am not receiving  automatic alters by email.

I hope this can help,

Gabriele

**Comment by vss888** [comment]
Dear Gabriele,

Thank you very much for your reply! I will certainly have a look at `selfkiller_node` struct in `multipipe.hpp`. I did not realize that this special node exists and is added to each graph.

Here is the source code of my minimal test:

``` c++
// g++ Test27.C -std=c++17 -pthread -o Test27 -I${FASTFLOW} -I${WINDFLOW}/wf
/******************************************************************************/
#include <windflow.hpp>

#include <cstdlib>
#include <iostream>
#include <memory>
#include <numeric>
#include <optional>
#include <vector>
/******************************************************************************/
using DataSet = std::vector<uint32_t>;
/******************************************************************************/
class SourceFunctor
{
public:
 SourceFunctor(const DataSet * const dataset): dataset(dataset) {}
 void operator()(wf::Source_Shipper<DataSet::value_type> & shipper) const
 { for(const auto & data: *dataset) shipper.push(data); }
private:
 const DataSet * const dataset;
};
/******************************************************************************/
using Sum = int64_t;
/******************************************************************************/
class SinkFunctor
{
public:
 SinkFunctor(void) : sum(new Sum{0}) {}
 void operator()(std::optional<DataSet::value_type> & input)
 { if(input) *sum += *input; else std::cout<<"End of stream"<<std::endl; }
 const Sum & GetSum(void) const { return *sum; }
private:
 std::shared_ptr<Sum> sum;
};
/******************************************************************************/
int main(void)
{
 const uint32_t nEvents = 100'000'000;
 DataSet dataset(nEvents);
 std::iota(dataset.begin(), dataset.end(), 0);
 std::cout<<"dataset[0]: "<<dataset[0]<<std::endl;
 std::cout<<"dataset[-1]: "<<dataset.back()<<std::endl;

 const Sum sum = std::accumulate(dataset.begin(), dataset.end(), Sum(0));
 std::cout<<"expected result a: "<<sum<<std::endl;
 std::cout<<"expected result t: "<<dataset.size()*(dataset.front()+dataset.back())/2<<std::endl;

 wf::PipeGraph graph("Test", wf::Execution_Mode_t::DEFAULT, wf::Time_Policy_t::INGRESS_TIME);

 SourceFunctor sourceFunctor(&dataset);
 wf::Source source = wf::Source_Builder(sourceFunctor)
     .withName("source")
     .withParallelism(1)
     .build();

 SinkFunctor sinkFunctor;
 wf::Sink sink = wf::Sink_Builder(sinkFunctor)
     .withName("sink")
     .withParallelism(1)
     .build();

 graph.add_source(source).add_sink(sink);
 std::cout<<"number of threads : "<<graph.getNumThreads()<<std::endl;
 graph.run();

 std::cout<<"Output: "<<sinkFunctor.GetSum()<<std::endl;
 std::cout<<"diff: "<<(sinkFunctor.GetSum()-sum)<<std::endl;

 return EXIT_SUCCESS;
}// end of function
/******************************************************************************/
```
The test requires a modified version of `node.hpp` with the following diff
``` diff
332c332
<             init_thread_affinity(attr, cpuId);
---
>             cpuid = init_thread_affinity(attr, cpuId);
350a351,352
>     int GetCPUId(void) const { return cpuid; }
> 
433a436
>     int             cpuid;
902a906,907
>         if(thread)
>             std::cout<<"ff_node::~ff_node: CPUId: "<<thread->GetCPUId()<<" myid: "<<myid<<std::endl;
```
i.e. `class ff_thread` gets a new private member ` int cpuid;`, new public function `int GetCPUId(void) const { return cpuid; }` and in function `spawn`, `init_thread_affinity(attr, cpuId);` is replaced with `cpuid = init_thread_affinity(attr, cpuId);`. Also, in the beginning of `~ff_node()` one should add `if(thread) std::cout<<"ff_node::~ff_node: CPUId: "<<thread->GetCPUId()<<" myid: "<<myid<<std::endl;`.

The program produces the following output:
``` none
dataset[0]: 0
dataset[-1]: 99999999
expected result a: 4999999950000000
expected result t: 4999999950000000
number of threads : 2
WindFlow Status Message: PipeGraph [Test] is running with 2 threads
--> DEFAULT (out-of-order) mode enabled
--> INGRESS_TIME policy enabled
--> Backpressure disabled
--> Non-blocking queues enabled
--> Pinning of threads enabled
End of stream
WindFlow Status Message: PipeGraph [Test] executed successfully
Output: 4999999950000000
diff: 0
ff_node::~ff_node: CPUId: 0 myid: 0
ff_node::~ff_node: CPUId: 1 myid: 1
ff_node::~ff_node: CPUId: 2 myid: 0
```
As you can see, the last node is presumably is the self-killer one, but it is destructed after the whole graph is finished running and all other nodes are finished destructing.

In a more realistic code, I manage CPU affinity of nodes with custom code, since I need to run not just one but dozens of graphs in parallel (with many thousands of graphs processed overall), and I need to know what nodes are done running such that I could start a new graph when there are enough of free CPU cores to run each node of the new graph on a dedicated CPU core. Right now, I mark a CPU core as free when the corresponding node destructor is called. But maybe, there is a way to know it earlier? **How could one detect that a given node is finished running (i.e. terminated) as early as possible?** That would be ideal solution. Alternatively, I could try to modify the code such that the self-killer node is destructed as soon as it is finished running.

Thank you very much for your help!

**Comment by vss888** [comment]
Another good solution would be to disable setting affinity to a dedicated CPU core for the self-killer node since the node terminates immediately after the application (graph?) has been launched.

**Comment by mencagli** [comment]
Hi,

apologize but I did not understand the issue that you have related to this node. The node terminates immediately, so why it is a critical problem for you? Disabling the pinning for a specific node is not supported at the moment (I have to check with my colleague who is maintaining FastFlow).

Can you please elaborate an use case where such a self-killer node generates problems to you?

Thanks,

**Comment by vss888** [comment]
Hi Gabriele,

Here is an over-simplified example: imagine you have a machine with 4 logical cores, you want to run on it 2 WindFlow graphs in parallel (each graph consisting of one source and one sink, so 2 nodes per graph). The default round-robin mapper of FastFlow will set 0,1,2 CPU affinities for the 1st graph (0,1 for the computing nodes and 2 for the self-killer node), and 3,0,1 affinities for the 2nd graph (3,0, for the computing nodes and 1 for the self-killer node). You can see that even though, technically, the machine has enough CPU cores to run the two graphs in parallel (with each node pinned to a dedicated CPU core), in reality one ends up running 2 nodes on core 0, and core 2 ends up being idle. This is the kind of problem I am trying to solve.

Thank you very much for your help!

**Comment by mencagli** [comment]
Uhm, ok I understand. Most of the times I have always run one app per 
process. But yes, I understand the problem. I will talk with my 
colleague to try to understand if a solution can be proposed shortly.

In the meanwhile, the only safe thing is to disable pinning, but of 
course this is not the optimal case...

I will get back to you soon,

Gabriele

************************************************
* Gabriele Mencagli                            *
* Associate Professor                          *
* Department of Computer Science               *
* University of Pisa, Italy                    *
* Tel: 0039 050 2213132                        *
* ***@***.***            *
************************************************

**Comment by vss888** [comment]
Thank you very much for your help, Gabriele!
