### ISSUE TITLE
Allowing nodes to process different types of input.

### ISSUE THREAD

**Issue by vss888** [ParaGroup/WindFlow#7]
Dear Gabriele, Massimo,

I have noticed that the static asserts in the WindFlow code forbid a node from processing different types of input at the same time. I can see it in the sink, map, builders, etc code. Here is an example:

``` c++
class MapFunctor
{
public:
 inline const void * operator()(const TypeOne * const & x) { return nullptr; }
 inline const void * operator()(const TypeTwo * const & x) { return nullptr; }
};
```
If both of the functions are present in the code, then the compilation fails with errors like these:
``` none
map.hpp: error: static assertion failed: WindFlow Compilation Error - Map_Replica does not have a valid functional logic:

   63 |     static_assert(isInPlaceNonRiched || isInPlaceRiched || isNonInPlaceNonRiched || isNonInPlaceRiched,
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
```
``` none
builders.hpp: error: static assertion failed: WindFlow Compilation Error - unknown signature passed to the Map_Builder:
  Candidate 1 : void(tuple_t &)
  Candidate 2 : void(tuple_t &, RuntimeContext &)
  Candidate 3 : result_t(const tuple_t &)
  Candidate 4 : result_t(const tuple_t &, RuntimeContext &)

  311 |     static_assert(!(std::is_same<tuple_t, std::false_type>::value || std::is_same<result_t, std::false_type>::value),
      |                                                             ^~~~~
```
If only one of the functions in `MapFunctor` is commented out, the code compiles. If both of the functions in `MapFunctor` are present and the `static_assert` lines above in the WindFlow source code are commented out, the code compiles.

Could you please let me know if there is an important technical reason to avoid processing more than one different input type by the same WindFlow node (assuming that the code thread safety is properly taken care of)? Or the errors above are only due to too restricting conditions in the `static_assert` calls?

Thank you very much for your help!

**Comment by mencagli** [comment]
Dear vss888,

unfortunately this is a constraint that cannot be easily circumvented with the present implementation. It is not a matter of static_asserts only. Data streams in WindFlow (as it happens in other streaming systems too) are typed, so you can receive inputs (from the same stream) all having the same type. Of course, there are different solutions for this problem, like using a hierarchy of types for your messages and dynamic_cast or other solutions more or less engineered. They can be efficient or not depending on your specific problem. The other option is to re-organize your application graph to process inputs having the same type in different operators.

I hope this can help!

Best,

Gabriele
